proto: add extra 'go_srcs' option
cockroachdb/rules_go pull request #1
Opened 2021-07-09 17:47 UTC by dt

This adds a 'go_srcs' attribute to the go_proto_library rule which
can be used to specify additional go source files that should be included
in the sources of the derived go_library. These can be required when using
non-proto-defined types in the generated proto, e.g. via 'casttype' which
are defined in files that also then reference proto-defined types,
creating a circular dependency between those files, which are intended
to be built as a single package. Thus those extra sources need to be
included in the go_proto_library's generated go_library.

2021-07-09 19:14 UTC, rickystewart requested changes

2021-07-09 19:14 UTC, rickystewart commented on proto/def.bzl
> +        "go_srcs": attr.label_list(allow_files = go_exts + asm_exts + cgo_exts),
add this attribute to the call to `attr.label_list()`:

`default = [],`

... and then the `getattr()` above shouldn't be necessary and you can just do `ctx.attr.go_srcs`.

2021-07-10 15:28 UTC, dt commented
Filed bazelbuild/rules_go#2920 upstream to see if that generates any discussion

2021-07-12 15:22 UTC, rickystewart approved these changes

2021-07-12 15:27 UTC, merged